[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "yourpackage"
version = "0.1.0"
description = "Tools for simulating and fitting spatial extremes processes
readme = "README.md"
requires-python = ">=3.9"
license = { text = "MIT" }
authors = [{ name = "Andy Yuan", email = "andy.yuan2tdsb@gmail.com" }]
dependencies = [
    "pandas>=2.0.0",
    "scipy>=1.10",
    "geopandas>=1.1",
    "polars>=1.0",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-cov", "ruff", "mypy"]

[project.urls]
Homepage = "https://github.com/andytyuan2/spatial-extremes"
